---
projects:
  yet-another:
    base:
      owner: cirocfc
      repo: yet-another
      branch: master

    protection:
      allow_deletions: false
      allow_force_pushes: false
      enforce_admins: false
      required_linear_history: false

      required_status_checks:
        strict: true

      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
