# Recommended features for protected branches
---
base:
  # Required
  branch: master

protection:
  # Required
  enforce_admins: true

  allow_deletions: false
  allow_force_pushes: false
  required_linear_history: false

  # Required
  required_status_checks:
    strict: true

  # Required
  required_pull_request_reviews:
    dismiss_stale_reviews: true
    require_code_owner_reviews: true

  # ONLY FOR ORGANIZATIONS
  # Required
  restrictions: null

locked:
  # ONLY FOR ORGANIZATIONS
  # Required
  restrictions:
    teams: []
    users: []
