---
projects:
  repository-name:
    base:
      # Required
      owner: Organization
      # Required
      repo: Repository
      # Required
      branch: master

    protection:
      allow_deletions: false
      allow_force_pushes: false
      # Required
      enforce_admins: true
      required_linear_history: true

      # Required
      required_status_checks:
        strict: true
        contexts:
          - Danger
          - circle-ci
          - Travis-CI

      # Required
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true

      # Required
      restrictions: null

    locked:
      # Required
      restrictions:
        teams:
          - owner-team-slug
