name: Generate Tags

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Configure GitHub App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ steps.app-token.outputs.token }}

      - name: Configure Git User
        run: |
          git config --global user.name ${{ vars.BOT_APP_USERNAME }}[bot]
          git config --global user.email ${{ vars.BOT_APP_EMAIL }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          scope: '@yetanothercode'
          always-auth: true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Authenticate on npmjs Registry
        run: |
          echo "@yetanothercode:registry=https://registry.npmjs.org/" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}



      - name: Install Packages
        run: yarn install

      - name: Create tags
        run: yarn lerna version --yes
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
